### ISSUE TITLE
Smuggler Error

### ISSUE THREAD

**Issue by PushkraJ99** [gotr00t0day/spyhunt#17]
Forgot to Add **lib** Folder in **tools/[smuggler](https://github.com/defparam/smuggler.git)** folder

**Comment by mayormaynotbeano** [comment]
I am experiencing the same issue after installing. Even after install.py, it does not include the lib folder in the smuggler directory.

**Comment by gotr00t0day** [comment]
Oh I see, the lib folder is grayed out. I will add it soon, thanks ;)

**Comment by mayormaynotbeano** [comment]
lmao
