### ISSUE TITLE
error concerning user agents

### ISSUE THREAD

**Issue by mayormaynotbeano** [gotr00t0day/spyhunt#19]
Error occurs when the random.choice uses:
    "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36 Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10",
    
which is the longest in the useragent script. Trying to rerun, but it keeps using this user agent. Could it be too long? and could Random be replaced with secrets? I made a pull for this :)

**Comment by gotr00t0day** [comment]
what error do you get?

**Comment by mayormaynotbeano** [comment]
413 - Entity too large. The random module also chokes on that user agent, as mentioned in my tests in one of the pull requests.

**Comment by mayormaynotbeano** [comment]
> Hi I know it's out of context here but can anyone tell me how to solve the "Invalid Api key" in Valhalla?

I'd say you have to use a valid API key lol. Did you get the API key from their website?

**Comment by mayormaynotbeano** [comment]
> Hi I know it's out of context here but can anyone tell me how to solve the "Invalid Api key" in Valhalla?

But if you want extensive support, I´d suggest opening a new issue, to not confuse the two.

**Comment by DhritimoyDas** [comment]
> > Hi I know it's out of context here but can anyone tell me how to solve the "Invalid Api key" in Valhalla?
> 
> But if you want extensive support, I´d suggest opening a new issue, to not confuse the two.

I did open an issue but  i got no response.

**Comment by DhritimoyDas** [comment]
Issue: https://github.com/gotr00t0day/valhalla/issues

**Comment by mayormaynotbeano** [comment]
> > > Hi I know it's out of context here but can anyone tell me how to solve the "Invalid Api key" in Valhalla?
> > 
> > 
> > But if you want extensive support, I´d suggest opening a new issue, to not confuse the two.
> 
> I did open an issue but i got no response.

But that is a completely different project, not related with spyhunt.........

**Comment by gotr00t0day** [comment]
I'll remove that one from the list

**Comment by gotr00t0day** [comment]
Fixed ;)

**Comment by mayormaynotbeano** [comment]
> Fixed ;)

THANKS!!
