### ISSUE TITLE
i have a problem with the buildwith module

### ISSUE THREAD

**Issue by mojidoji** [gotr00t0day/spyhunt#21]
hi, i installed the tool and them i was going to use it but after i was going to use i had this error 

python3 spyhunt.py -h
Traceback (most recent call last):
  File "/sec/root/spyhunt/spyhunt.py", line 3, in <module>
    from builtwith import builtwith
ModuleNotFoundError: No module named 'builtwith'

**Comment by gotr00t0day** [comment]
pip3 install builtwith

**Comment by gotr00t0day** [comment]
You need to install the requirements

**Comment by mojidoji** [comment]
> You need to install the requirements

hmm i press to install but it says the connection problem and stuff, i'm testing it on segfault server, hmm is that a problem that can't install on that? wanted to test some

**Comment by mojidoji** [comment]
> You need to install the requirements

thank you it solved, thank you again , tho i have a question sir, i saw the video, can you provide the sheet thing ? from basic recon? and also thank you for the tool, and other question is, where can i find that ffuf and nuclei template that u used in the video? thanks

**Comment by gotr00t0day** [comment]
> > You need to install the requirements
> 
> thank you it solved, thank you again , tho i have a question sir, i saw the video, can you provide the sheet thing ? from basic recon? and also thank you for the tool, and other question is, where can i find that ffuf and nuclei template that u used in the video? thanks

I'm just using tags with nuclei, those templates are already in nuclei-templates.
