### ISSUE TITLE
error

### ISSUE THREAD

**Issue by icepolylol** [gotr00t0day/spyhunt#24]
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by Dexorb** [comment]
me pasa igual.

**Comment by gotr00t0day** [comment]
You're installing it wrong. You need to clone the repo and then install the requirements `pip3 install -r requirements.txt` and then the install file `python3 install.py` ;)

**Comment by seenishahan** [comment]
> ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

move setup.py from 'paramspider' to 'spyhunt' folder.
Run 'sudo python3 install.py'

**Comment by Dexorb** [comment]
> > ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
> 
> move setup.py from 'paramspider' to 'spyhunt' folder. Run 'sudo python3 install.py'

-----------------------

Nice solution
