### ISSUE TITLE
Getting this loading error when Installing  Spyhunt. (Latest Version)

### ISSUE THREAD

**Issue by knvpavan** [gotr00t0day/spyhunt#26]
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Kali-Linux.

└─# python3 --version
Python 3.11.8

└─# pip3 --version
pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.11)

Could someone help?

**Comment by gotr00t0day** [comment]
You need to install the requirements.txt and then run the install.py file ;)
