### ISSUE TITLE
js file error

### ISSUE THREAD

**Issue by mojidoji** [gotr00t0day/spyhunt#27]
![gh](https://github.com/gotr00t0day/spyhunt/assets/126080465/67191fa3-4d52-4d45-80bf-0a8260742f53)

i have this problem when i want to do js search

**Comment by tobiasasa** [comment]
It says it explicitly you must respect the scheme try with htttp:// or htttps:// instead of www.
I hope it helps! Regards

**Comment by gotr00t0day** [comment]
> ![gh](https://private-user-images.githubusercontent.com/126080465/331261275-67191fa3-4d52-4d45-80bf-0a8260742f53.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTI1OTgsIm5iZiI6MTcxNTg5MjI5OCwicGF0aCI6Ii8xMjYwODA0NjUvMzMxMjYxMjc1LTY3MTkxZmEzLTRkNTItNGQ0NS04MGJmLTBhODI2MDc0MmY1My5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMDQ0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWNmNWJhMWJiZTNmY2JkNGJiNTU1YmU4ZGE3MWY3ZDRhZGMwYTdiMzQzNzc0ZGM4ZDAxYjM2M2FmNzE1YzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vPNu_7pMp1dOHTkDWuxEwFOzizrIMHtn5LRxW2t6R9k)
> 
> i have this problem when i want to do js search

You need to enter the entire url, https://www.site.com :P
