### ISSUE TITLE
Probe error and -st

### ISSUE THREAD

**Issue by spike-666** [gotr00t0day/spyhunt#29]
Using -p or --probe option the following error:

/bin/sh: 1: httprobe: not found
/bin/sh: 1: anew: not found

also no -st (SubDomainTakeover) Option in this version.

Thank you for the awesome tool as always.

EDIT: Re-ran the install.py and it fixed the PROBE error, but still no -st option.

**Comment by gotr00t0day** [comment]
> Using -p or --probe option the following error:
> 
> /bin/sh: 1: httprobe: not found /bin/sh: 1: anew: not found
> 
> also no -st (SubDomainTakeover) Option in this version.
> 
> Thank you for the awesome tool as always.
> 
> EDIT: Re-ran the install.py and it fixed the PROBE error, but still no -st option.

You had to run the install.py which installs all those tools. I'm still working on the subdomain takeover script, it will be released in later versions of the tool.

**Comment by spike-666** [comment]
Thanks mang!
