### ISSUE TITLE
Spyhunt installation problem

### ISSUE THREAD

**Issue by serkaneris** [gotr00t0day/spyhunt#33]
While installing Spyhunt on **Kali** Linux **2024**, I suddenly see a cursor on a black screen and it stays that way. When I restart the operating system, the terminal interface comes up and I cannot access **Gnome** gui. 
Before starting the installation, I ran apt update and apt upgrade. And then I installed the dependencies with pip3.
I am sharing a screenshot of the last place I saw before I received the error during spyhunt installation. Maybe it could be helpful in diagnosing the problem.
[
![IMG_5025](https://github.com/gotr00t0day/spyhunt/assets/10685831/60536c52-53d2-4d30-8c43-a024464ca8f3)
](url)

**Comment by tobiasasa** [comment]
Are you running spyhunt inside the github project? 

Try that, if it doesn't work let me know and we'll try to fix it together.

**Comment by serkaneris** [comment]
I follow the steps below.
1 git clone https://github.com/gotr00t0day/spyhunt.git
2 cd spyhunt
3 pip3 install -r requirements.txt
4 sudo python3 install.py

**Comment by tobiasasa** [comment]
Can check on the gootr00t0day, youtube channel, to install it successfully
