### ISSUE TITLE
ModuleNotFoundError: No module named 'builtwith'

### ISSUE THREAD

**Issue by Ym-Mm0t** [gotr00t0day/spyhunt#34]
Hi, i recently install the version 1.11 of Spyhunt, but i can't run it.

Executing give me this : 

─$ sudo python3 spyhunt.py -s test.com
Traceback (most recent call last):
  File "/opt/spyhunt/spyhunt.py", line 3, in <module>
    from builtwith import builtwith
ModuleNotFoundError: No module named 'builtwith'

And the requirements are good : 
─$ pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: builtwith in /home/sam/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (1.3.4)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.31.0)
Requirement already satisfied: shodan in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (1.30.1)
Requirement already satisfied: mmh3 in /home/sam/.local/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (4.1.0)
Requirement already satisfied: PyExecJS in /home/sam/.local/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (1.5.1)
Requirement already satisfied: python3-nmap in /home/sam/.local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 8)) (4.12.3)
Requirement already satisfied: fake-useragent in /home/sam/.local/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (1.5.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from builtwith->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: simplejson in /usr/lib/python3/dist-packages (from python3-nmap->-r requirements.txt (line 7)) (3.19.2)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->-r requirements.txt (line 8)) (2.5)

**Comment by mayormaynotbeano** [comment]
Hey! Are you installing the packages within a Venv, and executing the script outside of it? Can you please give more detail on your current conditions?

**Comment by tobiasasa** [comment]
Check ur virtual enviorment, maybe its the version, check in requierments what version use, and try another.
source /path/to/your/virtualenv/bin/activate
python3 -c "import builtwith; print(builtwith.__version__)"
sudo python3 spyhunt.py -s test.com
Run :)

**Comment by Ym-Mm0t** [comment]
> Hey! Are you installing the packages within a Venv, and executing the script outside of it? Can you please give more detail on >your current conditions?

Hi, thanks for the reply, i'm running on WLS linux, and no, i just reinstall them with pip3, but still hasn't solved anything

> Check ur virtual enviorment, maybe its the version, check in requierments what version use, and try another.
>source /path/to/your/virtualenv/bin/activate
>python3 -c "import builtwith; print(builtwith.version)"
>sudo python3 spyhunt.py -s test.com
>Run :)

Hi, thanks for the reply, Already try it, didn't solve anything too

**Comment by tobiasasa** [comment]
Can see in gotr00t0day youtube channel, how set up, i think so.

**Comment by gotr00t0day** [comment]
I think is because you're using "sudo" to run spyhunt and you didn't use sudo to install the requirements. Just "sudo pip3 install -r requirements" and try again.

**Comment by Ym-Mm0t** [comment]
> I think is because you're using "sudo" to run spyhunt and you didn't use sudo to install the requirements. Just "sudo pip3 install -r requirements" and try again.

Hi, thanks for the reply, so yes, it worked, but now it's subfinder & assetfinder x), they're not found in /bin/sh, do i have to move them ?
