### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by psych4cker** [gotr00t0day/spyhunt#39]
when installing requirement.txt, that error occurring 
![Screenshot from 2024-07-03 17-47-55](https://github.com/gotr00t0day/spyhunt/assets/162889818/1c59ea50-740a-4876-83e5-aaf9f94849e5)

and also "error: metadata-generation-failed" that one
![Screenshot from 2024-07-03 17-47-23](https://github.com/gotr00t0day/spyhunt/assets/162889818/43759655-fa75-4639-b57e-32883684d17f)

**Comment by gotr00t0day** [comment]
That's not a spyhunt issue, more like a python issue.

**Comment by psych4cker** [comment]
how can I solve it??
