### ISSUE TITLE
A little help with the installation

### ISSUE THREAD

**Issue by no0neismrji** [gotr00t0day/spyhunt#40]
Hi bro ! 

Thank you for your work ! Your tool will save my time ! 

In the installation step there is a little mistake : 
at lines 147 in install.py :     
commands(r"git clone https://github.com/devanshbatham/paramspider | cd paramspider | pip3 install")

The problem is on the end of the command : "pip3 install"

My solution :
commands(r"git clone https://github.com/devanshbatham/paramspider | cd paramspider | python3 setup.py install")

There is an additional install with pip : 

The error when i first run your script : 
ModuleNotFoundError: No module named 'alive_progress'

My solution : 
pip install alive-progress 
or 
Add to the requirements.txt
alive-progress 

Thank you again bro :)

**Comment by gotr00t0day** [comment]
> Hi bro !
> 
> Thank you for your work ! Your tool will save my time !
> 
> In the installation step there is a little mistake : at lines 147 in install.py : commands(r"git clone https://github.com/devanshbatham/paramspider | cd paramspider | pip3 install")
> 
> The problem is on the end of the command : "pip3 install"
> 
> My solution : commands(r"git clone https://github.com/devanshbatham/paramspider | cd paramspider | python3 setup.py install")
> 
> There is an additional install with pip :
> 
> The error when i first run your script : ModuleNotFoundError: No module named 'alive_progress'
> 
> My solution : pip install alive-progress or Add to the requirements.txt alive-progress
> 
> Thank you again bro :)

Thank you, I will fix the issues soon.
