### ISSUE TITLE
parameter miner problem

### ISSUE THREAD

**Issue by Caf3sp0re** [gotr00t0day/spyhunt#47]
Extracting parameters from HTML and JavaScript...
Traceback (most recent call last):
  File "/home/myname/Tools/spyhunt/spyhunt.py", line 1914, in <module>
    main(args.param_miner, args.wordlist, args.concurrency)
  File "/home/cafespore/Tools/spyhunt/spyhunt.py", line 1887, in main
    with open(wordlist, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by gotr00t0day** [comment]
> Extracting parameters from HTML and JavaScript... Traceback (most recent call last): File "/home/myname/Tools/spyhunt/spyhunt.py", line 1914, in main(args.param_miner, args.wordlist, args.concurrency) File "/home/cafespore/Tools/spyhunt/spyhunt.py", line 1887, in main with open(wordlist, 'r') as file: ^^^^^^^^^^^^^^^^^^^ TypeError: expected str, bytes or os.PathLike object, not NoneType

Show me the arguments that you used? You probably didn't enter a wordlist

**Comment by Caf3sp0re** [comment]
> > Extracting parameters from HTML and JavaScript... Traceback (most recent call last): File "/home/myname/Tools/spyhunt/spyhunt.py", line 1914, in main(args.param_miner, args.wordlist, args.concurrency) File "/home/cafespore/Tools/spyhunt/spyhunt.py", line 1887, in main with open(wordlist, 'r') as file: ^^^^^^^^^^^^^^^^^^^ TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> Show me the arguments that you used? You probably didn't enter a wordlist

Yeah your right,i didn't enter any wordlist,dumb me lol

**Comment by gotr00t0day** [comment]
> > > Extracting parameters from HTML and JavaScript... Traceback (most recent call last): File "/home/myname/Tools/spyhunt/spyhunt.py", line 1914, in main(args.param_miner, args.wordlist, args.concurrency) File "/home/cafespore/Tools/spyhunt/spyhunt.py", line 1887, in main with open(wordlist, 'r') as file: ^^^^^^^^^^^^^^^^^^^ TypeError: expected str, bytes or os.PathLike object, not NoneType
> > 
> > 
> > Show me the arguments that you used? You probably didn't enter a wordlist
> 
> Yeah your right,i didn't enter any wordlist,dumb me lol

No problem, I will add some error handling.
