### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by PlugCodes** [gotr00t0day/spyhunt#5]
ERROR: Could not find a version that satisfies the requirement codecs (from versions: none)
ERROR: No matching distribution found for codecs

**Comment by 4ndymcfly** [comment]
> ERROR: Could not find a version that satisfies the requirement codecs (from versions: none) ERROR: No matching distribution found for codecs

I think that since codecs is a built-in module, you don't need to install it using pip.

**Comment by PlugCodes** [comment]
> > ERROR: Could not find a version that satisfies the requirement codecs (from versions: none) ERROR: No matching distribution found for codecs
> 
> I think that since codecs is a built-in module, you don't need to install it using pip.

How would I download it then

**Comment by gotr00t0day** [comment]
> ERROR: Could not find a version that satisfies the requirement codecs (from versions: none) ERROR: No matching distribution found for codecs

pip3 install codecs?

**Comment by 4ndymcfly** [comment]
> > > ERROR: Could not find a version that satisfies the requirement codecs (from versions: none) ERROR: No matching distribution found for codecs
> 
> > 
> 
> > I think that since codecs is a built-in module, you don't need to install it using pip.
> 
> 
> 
> How would I download it then

Try this:
Open a terminal, type these commands, `python3` and then `import codecs`, if you press enter and do not receive any errors, you do not need to import codecs.

**Comment by Ahmedxemam** [comment]
> > ERROR: Could not find a version that satisfies the requirement codecs (from versions: none) ERROR: No matching distribution found for codecs
> 
> pip3 install codecs?

install it from py repo on it's on and remove it from requirements.txt

**Comment by Ahmedxemam** [comment]
i have this error ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by gotr00t0day** [comment]
> i have this error ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Because you're not running the command correctly. Use this `pip3 install -r requirements.txt` and then `python3 install.py`

**Comment by Ahmedxemam** [comment]
I did and still have same error
