### ISSUE TITLE
issue importing wayback

### ISSUE THREAD

**Issue by Kolden12** [gotr00t0day/spyhunt#58]
Everytime I try to run anything I get the error regarding wayback seen below. I verified that all Requirements were installed. 

```
Traceback (most recent call last):
  File "/opt/spyhunt/spyhunt.py", line 16, in <module>
    from waybackpy import WaybackMachine
ImportError: cannot import name 'WaybackMachine' from 'waybackpy' (/opt/spyhunt/venv/lib/python3.12/site-packages/waybackpy/__init__.py)
```

**Comment by gotr00t0day** [comment]
> Everytime I try to run anything I get the error regarding wayback seen below. I verified that all Requirements were installed.
> 
> ```
> Traceback (most recent call last):
>   File "/opt/spyhunt/spyhunt.py", line 16, in <module>
>     from waybackpy import WaybackMachine
> ImportError: cannot import name 'WaybackMachine' from 'waybackpy' (/opt/spyhunt/venv/lib/python3.12/site-packages/waybackpy/__init__.py)
> ```

Fixed!

**Comment by Kolden12** [comment]
Works now thank you so much! Been playing with it all day thanks for such a fast response!
