### ISSUE TITLE
Unexpected error during crawl

### ISSUE THREAD

**Issue by ringawy** [gotr00t0day/spyhunt#59]
python3 spyhunt.py -j 

Unexpected error during crawl: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'                                                                                                          
No JavaScript files found.

**Comment by gotr00t0day** [comment]
You're doing t wrong.

**python3 spyhunt.py -j  https://domain.com --depth 5 --save javascriptfile.txt -c 20**
