### ISSUE TITLE
spyhunt

### ISSUE THREAD

**Issue by lfillaz** [gotr00t0day/spyhunt#6]
███████╗██████╗ ██╗   ██╗██╗  ██╗██╗   ██╗███╗   ██╗████████╗
██╔════╝██╔══██╗╚██╗ ██╔╝██║  ██║██║   ██║████╗  ██║╚══██╔══╝
███████╗██████╔╝ ╚████╔╝ ███████║██║   ██║██╔██╗ ██║   ██║   
╚════██║██╔═══╝   ╚██╔╝  ██╔══██║██║   ██║██║╚██╗██║   ██║   
███████║██║        ██║   ██║  ██║╚██████╔╝██║ ╚████║   ██║   
╚══════╝╚═╝        ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝
V 1.8
By c0deninja

/bin/sh: 1: subfinder: not found
/bin/sh: 1: ./tools/assetfinder: Exec format error
┌─[parrot@parrot]─[~/spyhunt]
└──╼ $

**Comment by gotr00t0day** [comment]
> ███████╗██████╗ ██╗ ██╗██╗ ██╗██╗ ██╗███╗ ██╗████████╗ ██╔════╝██╔══██╗╚██╗ ██╔╝██║ ██║██║ ██║████╗ ██║╚══██╔══╝ ███████╗██████╔╝ ╚████╔╝ ███████║██║ ██║██╔██╗ ██║ ██║ ╚════██║██╔═══╝ ╚██╔╝ ██╔══██║██║ ██║██║╚██╗██║ ██║ ███████║██║ ██║ ██║ ██║╚██████╔╝██║ ╚████║ ██║ ╚══════╝╚═╝ ╚═╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝ ╚═══╝ ╚═╝ V 1.8 By c0deninja
> 
> /bin/sh: 1: subfinder: not found /bin/sh: 1: ./tools/assetfinder: Exec format error ┌─[parrot@parrot]─[~/spyhunt] └──╼ $

you need to run the install.py file. python3 install.py

**Comment by lfillaz** [comment]
I did it and I will do it again. I had no problem with version 2.0, but
this version has this problem.
