### ISSUE TITLE
Error execution

### ISSUE THREAD

**Issue by tXambe** [gotr00t0day/spyhunt#61]
Hello,

when I run the script I have the follow error:

```
sudo python3 spyhunt.py -j https://testphp.vulnweb.com --depth 4  -c 20
Traceback (most recent call last):
  File "/opt/TOOLS/spyhunt/spyhunt.py", line 39, in <module>
    import nmap3
ModuleNotFoundError: No module named 'nmap3'
```
I have installed everything that comes with requeriments.txt and python3-nmap , but nothing, don't run.

A greeting and thanks

**Comment by gotr00t0day** [comment]
> Hello,
> 
> when I run the script I have the follow error:
> 
> ```
> sudo python3 spyhunt.py -j https://testphp.vulnweb.com --depth 4  -c 20
> Traceback (most recent call last):
>   File "/opt/TOOLS/spyhunt/spyhunt.py", line 39, in <module>
>     import nmap3
> ModuleNotFoundError: No module named 'nmap3'
> ```
> 
> I have installed everything that comes with requeriments.txt and python3-nmap , but nothing, don't run.
> 
> A greeting and thanks

I fixed that in early releases, you need to use --update to update and try again.

**Comment by tXambe** [comment]
Hello,

I will try and let you know.

Thanks
