### ISSUE TITLE
autorecon fail

### ISSUE THREAD

**Issue by tXambe** [gotr00t0day/spyhunt#63]
Hello,

when I run

```
sudo python3 spyhunt.py -ar https://altoromutual.com
```

fail the execution

```
on 0: Crawling https://altoromutual.com for links...
on 0: Found 34 links from crawling.
on 1: Extracting JavaScript files from links...
on 1: Found 2 JavaScript files.
on 2: Found 2 waybackurls.
on 3: Found 0 Open Ports.
on 3: Open Ports: 
Running autorecon |████████████████⚠︎                       | (!) 4/10 [40%] in 31.3s (0.13/s) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='altoromutual.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/TOOLS/spyhunt/spyhunt.py", line 2677, in <module>
    asyncio.run(main(target_url))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/TOOLS/spyhunt/spyhunt.py", line 2625, in main
    getheaders = await headers_info(target)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/TOOLS/spyhunt/spyhunt.py", line 2492, in headers_info
    r = s.get(target, verify=False, headers=header)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='altoromutual.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)"))
```

A greeting and thanks

**Comment by gotr00t0day** [comment]
> Hello,
> 
> when I run
> 
> ```
> sudo python3 spyhunt.py -ar https://altoromutual.com
> ```
> 
> fail the execution
> 
> ```
> on 0: Crawling https://altoromutual.com for links...
> on 0: Found 34 links from crawling.
> on 1: Extracting JavaScript files from links...
> on 1: Found 2 JavaScript files.
> on 2: Found 2 waybackurls.
> on 3: Found 0 Open Ports.
> on 3: Open Ports: 
> Running autorecon |████████████████⚠︎                       | (!) 4/10 [40%] in 31.3s (0.13/s) 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 203, in _new_conn
>     sock = connection.create_connection(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/socket.py", line 976, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
>     response = self._make_request(
>                ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 492, in _make_request
>     raise new_e
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 468, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 611, in connect
>     self.sock = sock = self._new_conn()
>                        ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 210, in _new_conn
>     raise NameResolutionError(self.host, self, e) from e
> urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 667, in send
>     resp = conn.urlopen(
>            ^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
>     retries = retries.increment(
>               ^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 515, in increment
>     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='altoromutual.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)"))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/TOOLS/spyhunt/spyhunt.py", line 2677, in <module>
>     asyncio.run(main(target_url))
>   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/opt/TOOLS/spyhunt/spyhunt.py", line 2625, in main
>     getheaders = await headers_info(target)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/TOOLS/spyhunt/spyhunt.py", line 2492, in headers_info
>     r = s.get(target, verify=False, headers=header)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
>     return self.request("GET", url, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
>     resp = self.send(prep, **send_kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
>     r = adapter.send(request, **kwargs)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 700, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='altoromutual.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ff8d84355e0>: Failed to resolve 'altoromutual.com' ([Errno -3] Temporary failure in name resolution)"))
> ```
> 
> A greeting and thanks

I couldn't reproduced the same error, everything works fine on my end. I did added some error handling.
