### ISSUE TITLE
api scan

### ISSUE THREAD

**Issue by Polaroiddev** [gotr00t0day/spyhunt#64]
spyhunt git:(main) ✗ python3 spyhunt.py -api https://mobifitness.ru/ --save apis
Scanning 272 endpoints for https://mobifitness.ru/
(venv) ➜  spyhunt git:(main) ✗ cat apis
cat: apis: No such file or directory

but on old ver all work good

**Comment by gotr00t0day** [comment]
-api doesnt have a save feature.

**Comment by Polaroiddev** [comment]
ty
