### ISSUE TITLE
Kali Nethunter  install.py error

### ISSUE THREAD

**Issue by hacker0x01hackerone** [gotr00t0day/spyhunt#65]
sudo python3 install.py I get the following error message on Kali nethunter
┌──(kali㉿localhost)-[~/spyhunt]
└─$ sudo python3 install.py
Traceback (most recent call last):
  File "/home/kali/spyhunt/install.py", line 197, in <module>
    main()
  File "/home/kali/spyhunt/install.py", line 121, in main
    is_wsl = check_wsl()
             ^^^^^^^^^^^
  File "/home/kali/spyhunt/install.py", line 81, in check_wsl
    with open('/proc/version', 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/proc/version'

**Comment by gotr00t0day** [comment]
Try running it as root

**Comment by gotr00t0day** [comment]
I did some error handling for WSL, but just to let you know we haven't tested spyhunt on kali nethunter. Try and install spyhunt again and let me know if you still get errors.

**Comment by hacker0x01hackerone** [comment]
it's working now thank you very much for the quick fix

**Comment by gotr00t0day** [comment]
Np
