### ISSUE TITLE
error

### ISSUE THREAD

**Issue by meysam420** [gotr00t0day/spyhunt#67]
hi

### ****spyhunt.py: error: unrecognized arguments: --heapdump****

By c0deninja

Updating the script...
Updating 3bb1a81..bb05ffa
error: Your local changes to the following files would be overwritten by merge:
        README.md
        install.py
        requirements.txt
        spyhunt.py
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        modules/heapdump_scan.py
Please move or remove them before you merge.
Aborting
Script updated!

**Comment by gotr00t0day** [comment]
You need to stash your work,  **git stash** and then try again.
