### ISSUE TITLE
Tools Unavailable 

### ISSUE THREAD

**Issue by PushkraJ99** [gotr00t0day/spyhunt#7]
Please add Smuggler, CVE 2022-29464, and Whatwaf in the tools folder.

There are only empty Folders with Name

**Comment by gotr00t0day** [comment]
That will be my next task

**Comment by gotr00t0day** [comment]
> Please add Smuggler, CVE 2022-29464, and Whatwaf in the tools folder.
> 
> There are only empty Folders with Name

It has now been fixed ;) x
