### ISSUE TITLE
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by Ahmedxemam** [gotr00t0day/spyhunt#9]
when i install the intall.py i get this

**Comment by mayormaynotbeano** [comment]
Hi! You might be encountering this issue when you are not within the same Directory as the setup.py script and the requirements.txt. Also, when you try to install the needed packages, please try executing 
`pip3 install -r requirements.txt` and then `sudo python3 install.py`.
Hope this helped! If not, feel free to reply :)

**Comment by Ahmedxemam** [comment]
I did and i still have that error and no i was in the same directory and it still gave an error

**Comment by Ahmedxemam** [comment]
![Uploading 20240427_055802.jpg…]()

**Comment by Ahmedxemam** [comment]
Heyyy i Figured it out i just needed to copy the setup file from paramspider to the spyhunt directory tnx for yall help <3
